name: Destroying the Infrastructure

on: 
  workflow_dispatch:

  workflow_run:
    workflows: ["Deploying the EKS infrastructure"]
    types:
      - completed
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_WORKSPACE: ${{ secrets.TF_WORKSPACE }}
  API_TOKEN: ${{ secrets.TF_API_TOKEN }}


jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      # - name: Download Terraform State Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: terraform-state
      #     path: ./terraform-state

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve
       